### ISSUE TITLE
Any update?

### ISSUE THREAD

**Issue by drmiaji** [andikapratama/furqan#1]
Dear brother,

Assalamu alaikum. I appreciate your good work. It is a very featured app but unfortunately, you did not continue the development. I am developing android apps for Islamic books and now trying to make it for the Quran and found yours. I am astonished to see your great work. 

I tried to fork it but failed. It might be because of old gradle and dependencies.

I wonder if you have any newer version of these source codes. If yes, could you please update that here? Thanks in advance for the good work and hope to see you soon. I do app for my Bengali speaking people and you can find my apps in the google playe by typing "drmiaji". 

With best regards,
Abdel-Baten

**Comment by andikapratama** [comment]
I've finally gotten around to updating it. It should work fine now.

**Comment by drmiaji** [comment]
Thanks for the update.  Fork worked without any problem. ¨

However, I get following error: What can be the solution? Thanks in advance for the assistance! 

E/SQLiteLog: (14) cannot open file at line 31278 of [2ef4f3a5b1]
E/SQLiteLog: (14) os_unix.c:31278: (2) open(/data/data/com.pratamalabs.furqan/databases/furqan.sqlite) - 
E/SQLiteDatabase: Failed to open database '/data/data/com.pratamalabs.furqan/databases/furqan.sqlite'.
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:207)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:191)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:669)
        at com.pratamalabs.furqan.repository.FurqanDatabase.checkDataBase(FurqanDatabase.kt:131)
        at com.pratamalabs.furqan.repository.FurqanDatabase.<init>(FurqanDatabase.kt:29)
        at com.pratamalabs.furqan.repository.FurqanDatabase$Companion.get(FurqanDatabase.kt:160)
        at com.pratamalabs.furqan.repository.FurqanDao.<clinit>(FurqanDao.kt:140)
        at com.pratamalabs.furqan.FurqanSettings.<clinit>(FurqanSettings.kt:32)
        at com.pratamalabs.furqan.StartActivity.<init>(StartActivity.kt:42)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
V/db log: database does't exist
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pratamalabs.furqan, PID: 4139
    java.lang.ExceptionInInitializerError
        at com.pratamalabs.furqan.FurqanSettings.<clinit>(FurqanSettings.kt:32)
        at com.pratamalabs.furqan.StartActivity.<init>(StartActivity.kt:42)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1024; regionStart=0; regionLength=-1
        at java.util.Arrays.checkOffsetAndCount(Arrays.java:1719)
        at libcore.io.IoBridge.write(IoBridge.java:487)
        at java.io.FileOutputStream.write(FileOutputStream.java:186)
        at com.pratamalabs.furqan.repository.FurqanDatabase.copyDataBase(FurqanDatabase.kt:74)
        at com.pratamalabs.furqan.repository.FurqanDatabase.<init>(FurqanDatabase.kt:34)
        at com.pratamalabs.furqan.repository.FurqanDatabase$Companion.get(FurqanDatabase.kt:160)
        at com.pratamalabs.furqan.repository.FurqanDao.<clinit>(FurqanDao.kt:140)
        at com.pratamalabs.furqan.FurqanSettings.<clinit>(FurqanSettings.kt:32) 
        at com.pratamalabs.furqan.StartActivity.<init>(StartActivity.kt:42) 
        at java.lang.Class.newInstance(Native Method) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1067) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
I/Process: Sending signal. PID: 4139 SIG: 9
Application terminated.

**Comment by andikapratama** [comment]
It said the database doesn't exist, Is this [file](https://github.com/andikapratama/furqan/blob/master/app/src/main/assets/furqan.sqlite) inside the apk? cos it works fine in my device.

**Comment by drmiaji** [comment]
Are you going to do any further update for this great app?

I failed to run it. I would be very grateful if you please update the repository.
